name: leaf2mqtt
version: 0.0.3
publish_to: 'none'
dependencies:
  dartnissanconnectna:
    git: https://gitlab.com/tobiaswkjeldsen/dartnissanconnectna
  dartnissanconnect:
    git: https://github.com/derich367/dartnissanconnect
  dartcarwings:
    git: https://github.com/Tobiaswk/dartcarwings
  mqtt_client: ^9.6.1
  logging: ^1.0.1
  collection: ^1.15.0-nullsafety.4
environment:
  sdk: ">=3.3.4 <4.0.0"
