name: leaf2mqtt
version: 0.0.1
dependencies:
  dartnissanconnectna:
    git: https://gitlab.com/tobiaswkjeldsen/dartnissanconnectna
  dartnissanconnect:
    git: https://gitlab.com/tobiaswkjeldsen/dartnissanconnect
  dartcarwings:
    git: https://gitlab.com/tobiaswkjeldsen/dartcarwings

  mqtt_client: ^7.0.0
